config/routes.rb
Rails.application.routes.draw do

  get 'todos', to: 'todos#index'
  get 'todos/new', to: 'todos#new'
  post 'todos', to: 'todos#create'
  get 'todos/list', to: 'todos#list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  patch 'todos/:id/complete', to: 'todos#complete', as: 'complete'
  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[show edit update destroy complete]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)

    if todo.save
      redirect_to root_path, notice: 'Se guardó la tarea con éxito'
    else
      redirect_to root_path, alert: 'No se guardó la tarea, intenta nuevamente'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to root_path, notice: 'La tarea se actualizó con éxito !'
    else
      redirect_to root_path, alert: 'La tarea no se guardó, intenta denuevo'
    end
  end

  def destroy
    @todo.destroy
    redirect_to root_path, notice: 'Se eliminó la tarea con éxito'
  end

  def complete
    @todo.completed = true
    @todo.save
    redirect_to root_path, notice: 'Has terminado tu tarea ! '
  end

  def list
    @todos = Todo.all
    @completed_todos = @todos.where('completed = ?', true)
    @uncompleted_todos = @todos.where('completed = ?', false)
  end
  
  private

  def set_todo
    @todo = Todo.find(params[:id])
  end
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba3RailsMati</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="navbar-brand" href="<%= root_path%>">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="<%= todos_list_path %>">Tareas completadas</a>
          <a class="nav-item nav-link" href="<%= todos_new_path%>">Crear una tarea</a>
        </div>
      </div>
    </nav>


    <br>
    <br>
    <br>
    <div class="container">
      <%= yield %>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: @todo, local: true) do |f|  %>

  <div class="form-group">
    <%= f.label :description %> <br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Confirmar", class:"btn btn-primary" %>
<% end %>

app/views/todos/edit.html.erb
<h2>Edit ! </h2>

<%= render 'form' %>

app/views/todos/index.html.erb
<h2>ToDo App !</h2>

<% if notice.present? %>
  <%= notice %>
<% end %>
<% if alert.present? %>
  <%= alert %>
<% end %>
<br>

<ul class="list-group">  
  <% @todos.each do |todo| %>
    <li class="list-group-item"> 
      <%= todo.description %> 
      <div style="padding-top:10px">
        <%= link_to "Ver", todo_path(todo), class:"btn btn-info" %> 
        <%= link_to "Editar", edit_todo_path(todo), class:"btn btn-success" %> 
        <%= link_to "Eliminar", todo_path(todo), class:"btn btn-danger", data: {confirm: 'Estas seguro?', method: :delete} %> 
        <%= link_to "Completar", complete_path(todo), class:"btn btn-warning", method: :patch %> 
      </div>
    </li>
  <% end %>  
</ul>
<br>
<%= link_to '+', todos_new_path, class:"btn btn-primary" %> 

app/views/todos/list.html.erb
  <div class="row">
    <div class="col-6">
      <h2>Tareas sin completar</h2>
    </div>
    <div class="col-6">
      <h2>Tareas completadas</h2>
    </div>
  
  </div>



<div class="row">
  <div class="col-6">
    <% @uncompleted_todos.each do |todo| %>
       <li class="list-group-item">
         <%= todo.description %>
       </li> 
    <% end %>
  </div> 
  
  <div class="col-6">
    <% @completed_todos.each do |todo| %>
      <li class="list-group-item">
        <%= todo.description %>
      </li> 
    <% end %>
  </div> 
  
</div>

app/views/todos/new.html.erb
<h2>New !</h2>
<%= render 'form' %>

app/views/todos/show.html.erb
<h2>Show !</h2>


<h4>Tarea:</h4>
<p><%= @todo.description %></p> <br>
<h4>Estado</h4>
<% if @todo.completed == true %>
  <p>Tu tarea está completada !</p>
<% else %>
  <p>Tu tarea aún no está completada !</p>
<% end %>